# Here, it is a docker compose config file, that includes frontend, 
# backend, and mysql services along with their environment variables.

version: '2'
services:
  frontend:
    container_name: mental-wellbeing-fe
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:8080"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  backend:
    container_name: mental-wellbeing-api
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    links:
      - db:mysql
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
        PORT: 5000
        SECRET_KEY: 'you-will-never-guess'
        DEBUG: 0
        FLASK_DEBUG: 0
        FLASK_APP: 'manage'
        DB_USERNAME: sapbuffalo
        DB_PASSWORD: sap
        DB_HOST: mysql
        DATABASE_NAME: sp_db
        MYSQL_ROOT_PASSWORD: root123

  db:
    container_name: mysql-db
    platform: linux/x86_64
    image: mysql:5.7.41
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./backend/db-init:/docker-entrypoint-initdb.d
    environment:
        MYSQL_USER: sapbuffalo
        MYSQL_PASSWORD: sap
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_DATABASE: sp_db

volumes:
  my-db:
