# Use an official Python runtime as a parent image
FROM python:3.8-slim

# make a local directory
RUN mkdir /backend

# set "/backend" as the working directory from which CMD, RUN, ADD references
WORKDIR /backend

# now copy all the files in this directory to /backend
ADD /backend/ .

# pip install the local requirements.txt
RUN pip install -r requirements.txt

# Listen to port 5000 at runtime
EXPOSE 5000

# Define our command to be run when launching the container
CMD flask run --host 0.0.0.0
