"""empty message

Revision ID: cac7932ad849
Revises: 
Create Date: 2023-12-09 22:16:10.420533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cac7932ad849'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suicide_rate_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('schizophrenia', sa.Integer(), nullable=True),
    sa.Column('bipolar_disorder', sa.Integer(), nullable=True),
    sa.Column('eating_disorders', sa.Integer(), nullable=True),
    sa.Column('anxiety_disorders', sa.Integer(), nullable=True),
    sa.Column('drug_use_disorders', sa.Integer(), nullable=True),
    sa.Column('depression', sa.Integer(), nullable=True),
    sa.Column('alcohol_use_disorders', sa.Integer(), nullable=True),
    sa.Column('prevalence_in_males', sa.Integer(), nullable=True),
    sa.Column('prevalence_in_females', sa.Integer(), nullable=True),
    sa.Column('country_population', sa.BigInteger(), nullable=True),
    sa.Column('predicted_suicide_rate', sa.Integer(), nullable=True),
    sa.Column('depressive_disorder_rates', sa.Integer(), nullable=True),
    sa.Column('prevalence_depressive_disorders_sex_both_age_all_ages', sa.Integer(), nullable=True),
    sa.Column('young_percentage', sa.Integer(), nullable=True),
    sa.Column('adult_percentage', sa.Integer(), nullable=True),
    sa.Column('old_percentage', sa.Integer(), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mental_health_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('create_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_datetime', sa.DateTime(), nullable=True))
        batch_op.alter_column('entity',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('code',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('schizophrenia',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('bipolar_disorder',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('eating_disorders',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('anxiety_disorders',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('drug_use_disorders',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('depression',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('alcohol_use_disorders',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('prevalence_in_males',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('prevalence_in_females',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('country_population',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('predicted_suicide_rate',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('depressive_disorder_rates',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('prevalence_depressive_disorders_sex_both_age_all_ages',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('young_percentage',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('adult_percentage',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('old_percentage',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mental_health_dataset', schema=None) as batch_op:
        batch_op.alter_column('old_percentage',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('adult_percentage',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('young_percentage',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('prevalence_depressive_disorders_sex_both_age_all_ages',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('depressive_disorder_rates',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('predicted_suicide_rate',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('country_population',
               existing_type=sa.BigInteger(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('prevalence_in_females',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('prevalence_in_males',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('alcohol_use_disorders',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('depression',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('drug_use_disorders',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('anxiety_disorders',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('eating_disorders',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('bipolar_disorder',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('schizophrenia',
               existing_type=sa.Integer(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.String(length=10),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('entity',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('update_datetime')
        batch_op.drop_column('create_datetime')
        batch_op.drop_column('id')

    op.drop_table('suicide_rate_predictions')
    # ### end Alembic commands ###
